### ISSUE TITLE
Make workflow keep going even if one branch of loop fails for as long as possible

### ISSUE THREAD

**Issue by jacobrh91** [jacobrh91/Swift-T-Variant-Calling#8]
Even if a given sample fails during the analysis within a loop, the rest of the loop should keep going until no further progress can be made without all of the samples being present (the "gathering" stages of the workflow, where branches are brought back together, such as the Joint Genotyping stage)

If we add this feature, it is obvious that we should then add another feature that would allow one to jump back into the workflow right before the "gathering" stage, either after the failure with the killed sample branch has been resolved, or the "gathering" can take place without the output of the failed branch.

Potential Solutions:
Write app calls that catch non-zero exits, do something, and return an exit code of 0 to swift

**Comment by j-woz** [comment]
Yes, that's the best approach for now.  Do you want to retry in any case? Do you have an example I can look at to see if there is more we can do?

**Comment by lsmainzer** [comment]
Hi, just my two cents here.
From the perspective of an analyst I believe this should be a user's choice, made inside the runfile before any analysis begins. I think the analyst should be able to choose between the following three options:

1) Allow all successful samples to continue processing to completion even if some samples in the batch have failed, anywhere. This will ensure that little node-hour waste occurs when some samples are "weird" for any reason. It will be up to the user to then go back by hand, figure out what went wrong and rerun the workflow only on the failed samples. Pretty common practice.

2) Quit the workflow altogether if any sample failed anywhere. This is useful if samples must be merged for combined processing at some point.

3) Pause processing on successful samples if a few others have failed. Continue with analysis after successful retry. This will introduce node-hour wastage if a large node reservation must be made up-front. But, this could be useful in cases where failure is merely due to a hardware failure, not the data themselves: flaky node, temporary drive i/o failure, etc. Can hardware failures be detected? Anyway, this option only makes sense if samples have to be analyzed together at some point. So the successful samples can keep going up to that point, then sit and wait for the failed ones to catch up before the results get merged together.

Hope this make sense.
Luda

**Comment by azzaea** [comment]
It is also helpful to note that Swift/T actually supports app retries to as much as `N` times, by exporting the environment variable: `TURBINE_APP_RETRIES=N`. To be able to see this in the log, one would need to export `TURBINE_LOG=1` first. (as per the [issue](https://github.com/swift-lang/swift-t/issues/116))

Thanks to @jmjwozniak for updating the [documentation](http://swift-lang.github.io/swift-t/guide.html#_app_retry) as well.
